---

- name: add mongo repo file
  template:
    src: repo.j2
    dest: /etc/yum.repos.d/mongodb-org-3.6.repo
  tags: mongodb
  become: true

- name: install mongodb
  yum:
    name: mongodb-org
    state: present
  tags: mongodb
  become: true

- name: configure mongodb
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
  tags: mongodb
  become: true

- name: run mongodb
  service:
    name: mongod
    state: started
    enabled: yes
  tags: mongodb
  become: true
