---

- hosts: all
  gather_facts: no

  tasks:
    - include_vars: "vars/common.yml"

    - name: install packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - nginx
